{% set name = "polygon-api-client" %}
{% set version = "1.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c1e68b6590a10c16e8e6ad09a36b5ce01c48c538b743fbeba0c8dfd15b27c5d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - VERSION={{ version }}
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - poetry
  run:
    - python >=3.8
    - certifi >=2022.5.18,<2024
    - setuptools
    - urllib3 >=1.26.9,<2
    - websockets >=10.3,<13

test:
  imports:
    - polygon
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/polygon-io/client-python
  summary: Polygon API client
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - yehoshuadimarsky
